services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${DBS_PASSWORD}
    platform: linux/amd64
    ports:
      - "1435:1433"
    volumes:
      - sqldata:/var/opt/mssql

  redis:
    image: redis:alpine
    command: redis-server --requirepass ${DBS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  sqldata:
  redisdata: